# Auto-generated by Terraform — production secrets are in Secret Manager.

PROJECT_ID=${project_id}
STORAGE_BUCKET=${storage_bucket}
PUBSUB_TOPIC=${pubsub_topic}
APP_URL=${app_url}
MODEL_PROVIDER=${model_provider}
INFERENCE_SERVICE_URL=${inference_url}
