# Auto-generated by Terraform — secrets are injected via Secret Manager in Cloud Run.
# For local dev, copy TELEGRAM_BOT_TOKEN and GEMINI_API_KEY from your own .env file.

APP_URL=${app_url}
MODEL_PROVIDER=${model_provider}
INFERENCE_SERVICE_URL=${inference_url}
GOOGLE_CLOUD_PROJECT=${project_id}
