# Auto-generated by Terraform — do not commit secrets from this file.
# Copy non-secret values to .env.local for local development.

VITE_FIREBASE_API_KEY=${firebase_api_key}
VITE_FIREBASE_AUTH_DOMAIN=${firebase_auth_domain}
VITE_FIREBASE_PROJECT_ID=${firebase_project_id}
VITE_FIREBASE_STORAGE_BUCKET=${firebase_storage_bucket}
VITE_FIREBASE_MESSAGING_SENDER_ID=${firebase_messaging_sender_id}
VITE_FIREBASE_APP_ID=${firebase_app_id}
VITE_GEMINI_API_KEY=${gemini_api_key}
VITE_MODEL_PROVIDER=${model_provider}
VITE_INFERENCE_URL=${inference_url}
VITE_APP_URL=${frontend_url}
VITE_BACKEND_URL=${backend_url}
