#!/usr/bin/env bash
# Pull Hire Lens config from Terraform outputs + generated production env files
# and write local .env files for frontend, bot, and backend.
#
# Prerequisites:
#   - terraform apply already run (generates *.env.production.generated)
#   - terraform.tfvars present with secrets (or set TELEGRAM_BOT_TOKEN / GEMINI_API_KEY)
#   - gcloud auth application-default login (for bot Firestore access)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$ROOT/terraform_new"
FRONTEND_GEN="$ROOT/apps/persona_probe/.env.production.generated"
BOT_GEN="$ROOT/apps/telegram-bot/.env.production.generated"
BACKEND_GEN="$ROOT/services/backend/.env.production.generated"
TFVARS="$TF_DIR/terraform.tfvars"

die() { echo "Error: $*" >&2; exit 1; }

[[ -d "$TF_DIR" ]] || die "terraform_new/ not found"

# ── Read secrets from terraform.tfvars (simple grep — no HCL parser) ─────────
read_tfvar() {
  local key="$1"
  if [[ -f "$TFVARS" ]]; then
    grep -E "^[[:space:]]*${key}[[:space:]]*=" "$TFVARS" 2>/dev/null \
      | head -1 \
      | sed -E 's/^[^=]+=[[:space:]]*"([^"]*)".*/\1/' \
      || true
  fi
}

TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-$(read_tfvar telegram_bot_token)}"
GEMINI_API_KEY="${GEMINI_API_KEY:-$(read_tfvar gemini_api_key)}"
MODEL_PROVIDER="${MODEL_PROVIDER:-$(read_tfvar model_provider)}"
PROJECT_ID="${PROJECT_ID:-$(read_tfvar project_id)}"

[[ -n "$PROJECT_ID" ]] || PROJECT_ID="$(cd "$TF_DIR" && terraform output -raw project_id 2>/dev/null || true)"
[[ -n "$MODEL_PROVIDER" ]] || MODEL_PROVIDER="gemini"

# ── Require generated files (run terraform apply if missing) ───────────────────
missing=0
for f in "$FRONTEND_GEN" "$BOT_GEN" "$BACKEND_GEN"; do
  if [[ ! -f "$f" ]]; then
    echo "Missing: $f"
    missing=1
  fi
done
if [[ "$missing" -eq 1 ]]; then
  die "Run 'cd terraform_new && terraform apply' first (generate_local_env_files = true)."
fi

# ── Parse a KEY=VALUE from a generated env file ──────────────────────────────
read_gen() {
  local file="$1" key="$2"
  grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- || true
}

# Frontend Firebase + Gemini from generated production file
VITE_FIREBASE_API_KEY="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_API_KEY)"
VITE_FIREBASE_AUTH_DOMAIN="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_AUTH_DOMAIN)"
VITE_FIREBASE_PROJECT_ID="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_PROJECT_ID)"
VITE_FIREBASE_STORAGE_BUCKET="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_STORAGE_BUCKET)"
VITE_FIREBASE_MESSAGING_SENDER_ID="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_MESSAGING_SENDER_ID)"
VITE_FIREBASE_APP_ID="$(read_gen "$FRONTEND_GEN" VITE_FIREBASE_APP_ID)"
VITE_GEMINI_API_KEY="${GEMINI_API_KEY:-$(read_gen "$FRONTEND_GEN" VITE_GEMINI_API_KEY)}"

STORAGE_BUCKET="$(read_gen "$BACKEND_GEN" STORAGE_BUCKET)"
PUBSUB_TOPIC="$(read_gen "$BACKEND_GEN" PUBSUB_TOPIC)"

[[ -n "$TELEGRAM_BOT_TOKEN" ]] || die "Set telegram_bot_token in terraform.tfvars or TELEGRAM_BOT_TOKEN env var"
[[ -n "$VITE_FIREBASE_API_KEY" ]] || die "Could not read Firebase config from $FRONTEND_GEN"

LOCAL_FRONTEND="http://localhost:3000"
LOCAL_BACKEND="http://localhost:8080"

# ── Write frontend .env.local ────────────────────────────────────────────────
cat > "$ROOT/apps/persona_probe/.env.local" <<EOF
# Generated by scripts/setup-local-from-cloud.sh — do not commit

APP_URL=${LOCAL_FRONTEND}

VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
VITE_MODEL_PROVIDER=${MODEL_PROVIDER}
VITE_INFERENCE_URL=
VITE_APP_URL=${LOCAL_FRONTEND}
VITE_BACKEND_URL=${LOCAL_BACKEND}
VITE_TELEGRAM_BOT_USERNAME=
EOF
echo "Wrote apps/persona_probe/.env.local"

# ── Write bot .env (polling mode — PORT 8081 to avoid backend conflict) ─────
cat > "$ROOT/apps/telegram-bot/.env" <<EOF
# Generated by scripts/setup-local-from-cloud.sh — do not commit

TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
APP_URL=${LOCAL_FRONTEND}
MODEL_PROVIDER=${MODEL_PROVIDER}
INFERENCE_SERVICE_URL=
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
PORT=8081
EOF
echo "Wrote apps/telegram-bot/.env"

# ── Write backend .env ───────────────────────────────────────────────────────
cat > "$ROOT/services/backend/.env" <<EOF
# Generated by scripts/setup-local-from-cloud.sh — do not commit

PROJECT_ID=${PROJECT_ID}
STORAGE_BUCKET=${STORAGE_BUCKET}
PUBSUB_TOPIC=${PUBSUB_TOPIC}
APP_URL=${LOCAL_FRONTEND}
MODEL_PROVIDER=${MODEL_PROVIDER}
INFERENCE_SERVICE_URL=
EOF
echo "Wrote services/backend/.env"

# ── Optional: clear Telegram webhook so local polling receives updates ─────────
if [[ "${DELETE_TELEGRAM_WEBHOOK:-1}" == "1" ]]; then
  echo "Clearing Telegram webhook (local bot uses long-polling)..."
  curl -sS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/deleteWebhook?drop_pending_updates=true" \
    | python3 -c "import sys,json; r=json.load(sys.stdin); print('Webhook:', 'cleared' if r.get('ok') else r)" \
    || echo "Warning: could not clear webhook — bot may not receive messages locally"
fi

echo ""
echo "Done. Local URLs:"
echo "  Frontend:  ${LOCAL_FRONTEND}"
echo "  Backend:   ${LOCAL_BACKEND}/health"
echo "  Bot:       http://localhost:8081 (polling mode)"
echo ""
echo "Next:"
echo "  gcloud auth application-default login   # Firestore for bot"
echo "  See docs/LOCAL_DEVELOPMENT.md"
