import React from 'react';
import { Navbar } from './Navbar';
import { Footer } from './Footer';
import { FullProfile } from '../types/index';

interface ResultsPageProps {
  result: FullProfile;
  onReset: () => void;
}

export function ResultsPage({ result, onReset }: ResultsPageProps) {
  const barColors = ["bg-blue-500", "bg-[#7c3aed]", "bg-green-500", "bg-yellow-500", "bg-pink-500"];

  const cardText = `┌───────────────────────────────────┐
USER: ${result.profile.login.padEnd(20)} [${(result.analysis?.archetype ?? "DEVELOPER").toUpperCase().slice(0, 10)}]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REPOS:    ${result.profile.public_repos}
TOP_LANG: ${result.languageStats?.[0] ? `${result.languageStats[0].language} (${result.languageStats[0].percentage}%)` : "N/A"}
ACTIVE:   ${result.commitPattern?.most_active_day?.toUpperCase() ?? "N/A"}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by PersonaProbe Intelligence
└───────────────────────────────────┘`;

  return (
    <div className="min-h-screen bg-[#0c1322] text-[#dce2f7] font-body">
      <Navbar />
      <main className="max-w-6xl mx-auto px-6 py-12 space-y-12">
        <button
          onClick={onReset}
          className="mb-8 flex items-center gap-2 text-[#958da1] hover:text-[#d2bbff] transition-colors font-mono text-xs uppercase tracking-[0.05em]"
        >
          <span className="material-symbols-outlined text-sm">arrow_back</span> Search Again
        </button>

        {/* SECTION A — Profile Header */}
        <section className="relative bg-[#141b2b] rounded-xl px-8 pb-8 pt-16 mt-16">
          <div className="absolute -top-12 left-8">
            <img src={result.profile.avatar_url} 
                 alt={result.profile.login}
                 className="w-24 h-24 rounded-full border-2 border-[#7c3aed] shadow-[0_0_20px_rgba(124,58,237,0.3)] object-cover" />
          </div>
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div>
              <a
                href={result.profile.html_url}
                target="_blank"
                rel="noreferrer"
                className="text-3xl font-headline font-bold text-[#dce2f7] glow-text tracking-[-0.02em] hover:text-[#d2bbff] transition-colors"
              >
                {result.profile.login}
              </a>
              <p className="text-[#ccc3d8] max-w-md font-body text-sm leading-relaxed mt-2">
                {result.profile.bio ?? "No bio available."}
              </p>
            </div>
            <div className="bg-[#523787]/20 px-4 py-2 rounded-full border border-[#7c3aed]/30 flex items-center gap-2">
              <span className="text-[#d2bbff] font-headline font-bold text-sm tracking-[-0.02em]">
                {result.analysis?.archetype ?? "Developer"}
              </span>
            </div>
          </div>
        </section>

        {/* SECTION B — Stats Row */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-8 rounded-xl bg-[#2e3545] hover:translate-y-[-4px] hover:shadow-[0_8px_32px_0_rgba(124,58,237,0.12)] transition-all duration-300">
            <div className="w-1 h-10 rounded-full bg-gradient-to-b from-[#d2bbff] to-[#7c3aed] mb-6" />
            <span className="font-mono text-xs tracking-[0.05em] uppercase text-[#958da1] block mb-3">
              Public Repositories
            </span>
            <div className="flex items-baseline gap-3 flex-wrap">
              <span className="font-headline text-5xl font-bold text-[#dce2f7] tracking-[-0.02em]">
                {result.profile.public_repos}
              </span>
            </div>
            <span className="font-mono text-[10px] tracking-[0.05em] uppercase text-[#958da1] mt-6 block">
              Total Repos
            </span>
          </div>
          <div className="p-8 rounded-xl bg-[#2e3545] hover:translate-y-[-4px] hover:shadow-[0_8px_32px_0_rgba(124,58,237,0.12)] transition-all duration-300">
            <div className="w-1 h-10 rounded-full bg-gradient-to-b from-[#d2bbff] to-[#7c3aed] mb-6" />
            <span className="font-mono text-xs tracking-[0.05em] uppercase text-[#958da1] block mb-3">
              Top Language
            </span>
            <div className="flex items-baseline gap-3 flex-wrap">
              <span className="font-headline text-5xl font-bold text-[#dce2f7] tracking-[-0.02em]">
                {result.languageStats?.[0]?.language ?? "N/A"}
              </span>
              {result.languageStats?.[0] && (
                <span className="font-headline text-2xl font-bold text-[#d2bbff]">
                  {result.languageStats[0].percentage}%
                </span>
              )}
            </div>
            <span className="font-mono text-[10px] tracking-[0.05em] uppercase text-[#958da1] mt-6 block">
              Primary Language
            </span>
          </div>
          <div className="p-8 rounded-xl bg-[#2e3545] hover:translate-y-[-4px] hover:shadow-[0_8px_32px_0_rgba(124,58,237,0.12)] transition-all duration-300">
            <div className="w-1 h-10 rounded-full bg-gradient-to-b from-[#d2bbff] to-[#7c3aed] mb-6" />
            <span className="font-mono text-xs tracking-[0.05em] uppercase text-[#958da1] block mb-3">
              Most Active
            </span>
            <div className="flex items-baseline gap-3 flex-wrap">
              <span className="font-headline text-5xl font-bold text-[#dce2f7] tracking-[-0.02em]">
                {result.commitPattern?.most_active_day ?? "N/A"}
              </span>
            </div>
            <span className="mt-3 inline-flex bg-[#523787] text-[#c3a6ff] rounded-full px-3 py-1 font-mono text-xs tracking-[0.05em] uppercase">
              {result.commitPattern?.pattern_label}
            </span>
            <span className="font-mono text-[10px] tracking-[0.05em] uppercase text-[#958da1] mt-6 block">
              Weekly Peak Activity
            </span>
          </div>
        </section>

        {/* SECTION C — Tech Stack */}
        <section>
          <h2 className="text-xl font-headline font-bold text-[#dce2f7] tracking-[-0.02em] flex items-center gap-3 mb-6">
            <div className="w-8 h-[2px] bg-gradient-to-r from-[#d2bbff] to-[#7c3aed] rounded-full" />Tech Stack
          </h2>
          <div className="p-8 rounded-xl bg-[#141b2b] space-y-8">
            {(result.languageStats ?? []).map((stat, index) => (
              <div className="space-y-2" key={stat.language}>
                <div className="flex justify-between font-mono text-xs tracking-[0.05em] uppercase mb-1">
                  <span className="text-[#dce2f7]">{stat.language}</span>
                  <span className="text-[#958da1]">{stat.percentage}%</span>
                </div>
                <div className="h-2 bg-[#070e1d] rounded-full overflow-hidden">
                  <div
                    className={`h-full ${barColors[index % barColors.length]} rounded-full transition-all duration-1000`}
                    style={{ width: `${stat.percentage}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* SECTION D — AI Analysis */}
        <section>
          <h2 className="text-xl font-headline font-bold text-[#dce2f7] tracking-[-0.02em] flex items-center gap-3 mb-6">
            <div className="w-8 h-[2px] bg-gradient-to-r from-[#d2bbff] to-[#7c3aed] rounded-full" />AI Analysis
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-xl bg-[#141b2b]">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-1 h-6 rounded-full bg-blue-400 flex-shrink-0" />
                <span className="material-symbols-outlined text-blue-400">chat_bubble</span>
                <h3 className="font-headline font-bold text-[#dce2f7] tracking-[-0.02em]">Personality Profile</h3>
              </div>
              <p className="text-sm text-[#ccc3d8] leading-relaxed">{result.analysis?.personality_summary ?? ""}</p>
            </div>
            <div className="p-6 rounded-xl bg-[#141b2b]">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-1 h-6 rounded-full bg-green-400 flex-shrink-0" />
                <span className="material-symbols-outlined text-green-400">check_circle</span>
                <h3 className="font-headline font-bold text-[#dce2f7] tracking-[-0.02em]">Strengths:</h3>
              </div>
              <ul className="space-y-2">
                {(result.analysis?.top_strengths ?? []).map((s, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-[#ccc3d8]">
                    <span className="w-1.5 h-1.5 rounded-full bg-green-400 mt-1.5 flex-shrink-0" />
                    {s}
                  </li>
                ))}
              </ul>
            </div>
            <div className="p-6 rounded-xl bg-[#141b2b]">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-1 h-6 rounded-full bg-amber-400 flex-shrink-0" />
                <span className="material-symbols-outlined text-amber-400">trending_up</span>
                <h3 className="font-headline font-bold text-[#dce2f7] tracking-[-0.02em]">Growth Area:</h3>
              </div>
              <p className="text-sm text-[#ccc3d8] leading-relaxed">{result.analysis?.blind_spot ?? ""}</p>
            </div>
            <div className="p-6 rounded-xl bg-[#141b2b]">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-1 h-6 rounded-full bg-green-400 flex-shrink-0" />
                <span className="material-symbols-outlined text-green-400">work</span>
                <h3 className="font-headline font-bold text-[#dce2f7] tracking-[-0.02em]">Recruiter View:</h3>
              </div>
              <p className="text-sm text-[#ccc3d8] leading-relaxed">{result.analysis?.recruiter_pitch ?? ""}</p>
            </div>
          </div>
        </section>

        {/* SECTION E — Share Card */}
        <section>
          <h2 className="text-xl font-headline font-bold text-[#dce2f7] tracking-[-0.02em] flex items-center gap-3 mb-6">
            <div className="w-8 h-[2px] bg-gradient-to-r from-[#d2bbff] to-[#7c3aed] rounded-full" />Share Your Profile
          </h2>
          <div className="p-8 rounded-xl bg-[#141b2b] flex flex-col items-center">
            <div className="w-full max-w-2xl p-8 bg-[#070e1d] rounded-xl font-mono text-sm relative overflow-hidden ghost-border text-[#dce2f7]">
              <pre>{cardText}</pre>
            </div>
            <div className="flex gap-4 mt-8 justify-center flex-wrap">
              <button
                onClick={() => navigator.clipboard.writeText(cardText)}
                className="gradient-primary text-[#3f008e] rounded-xl font-headline font-bold px-6 py-3 hover:brightness-110 active:scale-95 transition-all flex items-center gap-2"
              >
                <span className="material-symbols-outlined text-sm">content_copy</span> Copy to Clipboard
              </button>
              <button
                onClick={() => {
                  const blob = new Blob([cardText], { type: "text/plain" });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = `${result.profile.login}-persona.txt`;
                  a.click();
                  URL.revokeObjectURL(url);
                }}
                className="bg-[#2e3545] text-[#ccc3d8] rounded-xl font-headline font-bold px-6 py-3 hover:bg-[#3e4555] active:scale-95 transition-all flex items-center gap-2 ghost-border"
              >
                <span className="material-symbols-outlined text-sm">download</span> Download .txt
              </button>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
