import React from 'react';
import { FullProfile } from '../types';

interface ShareCardProps {
  profile: FullProfile;
}

export const ShareCard: React.FC<ShareCardProps> = ({ profile }) => {
  const text = `━━━━━━━━━━━━━━━━━━━━━━━━━━
👤 @${profile.profile.login} | ${profile.analysis.archetype}
━━━━━━━━━━━━━━━━━━━━━━━━━━
🧠 ${(profile.languageStats || []).slice(0, 3).map(l => `${l.language} (${l.percentage}%)`).join(', ')}
⚡ ${profile.commitPattern?.pattern_label || 'N/A'} | ${profile.profile.public_repos} public repos
💬 ${profile.analysis.personality_summary}
✅ Strengths: ${(profile.analysis.top_strengths || []).join(', ')}
📈 Growth: ${profile.analysis.blind_spot}
💼 ${profile.analysis.recruiter_pitch}
━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by PersonaProbe 🕵️`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      alert('Copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${profile.profile.login}_persona.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-800 p-6 rounded-xl border border-gray-700 w-full space-y-4">
      <h3 className="text-xl font-bold text-white">Share Your Persona</h3>
      <pre className="bg-gray-900 text-gray-300 font-mono text-xs p-4 rounded-lg overflow-x-auto whitespace-pre-wrap border border-gray-700">
        {text}
      </pre>
      <div className="flex gap-2">
        <button
          onClick={handleCopy}
          className="flex-1 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md font-medium transition-colors"
        >
          Copy to Clipboard
        </button>
        <button
          onClick={handleDownload}
          className="flex-1 bg-gray-700 hover:bg-gray-600 text-white px-4 py-2 rounded-md font-medium transition-colors"
        >
          Download .txt
        </button>
      </div>
    </div>
  );
};
